### ISSUE TITLE
Reference path containing spaces can not be opened

### ISSUE THREAD

**Issue by gilgwath** [Mermade/openapi-lint-vscode#8]
Hello everybody

When I try to run "OpenAPI Resolve and lint" on my OpenAPI 3 spec I get a "no such file or directory" error:

```
Your OpenAPI document is not valid :( 
#/ 
ENOENT: no such file or directory, open 'c:\Users\fasi\Documents\Idea%20Projects\myProject\web_api_gateway\src\main\resources\openapi\AssessmentConfiguration.yaml'. 
```

The "offending" code snipped is:

```
responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: './AssessmentConfiguration.yaml#/components/schemas/AssessmentConfiguration'
```

Like you can see my files are checked-in into a InteliJ IDEA Project, which usually reside in "Idea Projects". I moved all the files to a dir called "tmp" in my home dir and the refs could be resolved no problem. I suspect that the space causes a hiccup when loading the file.

As a temporary work around I moved my source to a new directory containing no spaces.

Information about my system:
- openapi-lint: 1.0.1
- VS code: 1.3.1.1
- Electron: 3.1.2
- Node.js: 10.2.0
- OS: Windows 10.0.16299

Thanks for making this plugin available and maintaining it :-)

**Comment by MikeRalphson** [comment]
According to Speccy https://github.com/wework/speccy/issues/141 this should have been fixed in oas-resolver v1.0.11. Commit https://github.com/Mermade/oas-kit/commit/722b75eaab32730943335c2866e8a2883906613b

**Comment by MikeRalphson** [comment]
Hmm, can't reproduce on linux with a directory containing a space...

**Comment by gilgwath** [comment]
I'll check again on Monday and try a few other ways to do the reference. Like absolute, '/' vs '\' etc. Thank you for looking into it :-)

**Comment by MikeRalphson** [comment]
No problem. I may have found a fix. Could you let me know if `v1.0.2` of the extension fixes it for you?

**Comment by bigozzi-inspect** [comment]
Hi, I have v1.0.2 of the extension but the problem still persist

**Comment by MikeRalphson** [comment]
:disappointed: ok, but thanks for reporting back!

**Comment by gilgwath** [comment]
Updated today and tested again. Confirm that the problem persists. It still escapes the space to '%20' and is unable to find the directory. Thanks for working on this. :-)

**Comment by MikeRalphson** [comment]
v1.0.3 released with latest libraries. Hopefully should fix this issue on windows.

**Comment by MikeRalphson** [comment]
Closing due to inactivity - but please feel free to reopen the issue if necessary.
